# Generated by Django 5.2.7 on 2025-11-01 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Course/Subject name', max_length=200)),
                ('grade_level', models.CharField(choices=[('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10'), ('11', 'Grade 11'), ('12', 'Grade 12')], help_text='Grade level', max_length=2)),
                ('year', models.IntegerField(help_text='Academic year (e.g., 2024)')),
                ('curriculum_type', models.CharField(choices=[('CAPS', 'CAPS'), ('IEB', 'IEB'), ('CAMBRIDGE', 'Cambridge'), ('IB', 'International Baccalaureate'), ('OTHER', 'Other')], default='CAPS', max_length=20)),
                ('schedule_days', models.JSONField(default=list, help_text="List of days the class meets (e.g., ['MON', 'WED', 'FRI'])")),
                ('schedule_times', models.CharField(blank=True, help_text="Class times (e.g., '14:00-15:30')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Subject description')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tutor', models.ForeignKey(limit_choices_to={'user_type': 'TUTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='taught_subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Material description')),
                ('material_type', models.CharField(choices=[('VIDEO', 'Video'), ('FILE', 'File/Document')], max_length=10)),
                ('video_url', models.URLField(blank=True, help_text='Full URL to the video', null=True)),
                ('video_platform', models.CharField(blank=True, choices=[('YOUTUBE', 'YouTube'), ('VIMEO', 'Vimeo'), ('DAILYMOTION', 'Dailymotion')], max_length=20, null=True)),
                ('file', models.FileField(blank=True, help_text='Upload document/file', null=True, upload_to='subject_materials/%Y/%m/')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_materials', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Full announcement text')),
                ('published_date', models.DateTimeField(help_text='When this announcement becomes visible')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['order', '-published_date'],
            },
        ),
        migrations.CreateModel(
            name='SubjectEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='subject_enrollments', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Subject Enrollment',
                'verbose_name_plural': 'Subject Enrollments',
                'ordering': ['-enrolled_date'],
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
